[package]
name = "rainy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
awc = "3"
reqwest = { version = "0.11", features = ["blocking", "json"] }
futures = "0.3"
